"""add_figure_records

Revision ID: dfc731ea5bf7
Revises: 0d214835f46e
Create Date: 2026-04-25 14:34:31.035410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dfc731ea5bf7'
down_revision: Union[str, Sequence[str], None] = '0d214835f46e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('figure_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('upload_id', sa.String(), nullable=False),
    sa.Column('paper_nct_id', sa.String(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('figure_index', sa.Integer(), nullable=False),
    sa.Column('figure_type', sa.String(), nullable=False),
    sa.Column('raw_interpretation', sa.Text(), nullable=False),
    sa.Column('structured_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('image_base64', sa.Text(), nullable=True),
    sa.Column('qdrant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_figure_records_upload_figure', 'figure_records', ['upload_id', 'figure_index'], unique=False)
    op.create_index(op.f('ix_figure_records_upload_id'), 'figure_records', ['upload_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_figure_records_upload_id'), table_name='figure_records')
    op.drop_index('ix_figure_records_upload_figure', table_name='figure_records')
    op.drop_table('figure_records')
    # ### end Alembic commands ###
